apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: internal-auth-compass
  namespace: compass-system
spec:
  jwtRules:
  - issuer: kubernetes/serviceaccount
    jwksUri: https://kubernetes.default.svc.cluster.local:443/openid/v1/jwks
    forwardOriginalToken: true
    fromHeaders:
    - name: X-Authorization
      prefix: "Bearer "
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: internal-authz-compass
  namespace: compass-system
spec:
  action: ALLOW
  rules:
    - to:
      - operation:
          methods:
          - GET
          paths:
          - /healthz*
      - operation:
          methods:
            - GET
          paths:
            - /readyz*
      - operation:
          methods:
            - GET
          paths:
            - /livez*
      - operation:
          methods:
            - GET
          paths:
            - /metrics*
    - to:
      - operation:
          ports:
          - "5432"
    - to:
      - operation:
          hosts:
          - compass.kyma.local
          - compass-mf.kyma.local
    - from:
      - source:
          requestPrincipals: ["*"]
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: internal-auth-kyma
  namespace: kyma-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hydra
  jwtRules:
  - issuer: "kubernetes/serviceaccount"
    jwksUri: https://kubernetes.default.svc.cluster.local:443/openid/v1/jwks
    forwardOriginalToken: true
    fromHeaders:
      - name: X-Authorization
        prefix: "Bearer "
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: internal-authz-kyma
  namespace: kyma-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hydra
  action: ALLOW
  rules:
    - from:
      - source:
          requestPrincipals: ['*']
## /var/run/secrets/kubernetes.io/serviceaccount/ca.crt in jwksResolverExtraRootCA of istio pilot config