apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leader-elector
  labels:
    app: { { .Chart.Name } }
    release: { { .Release.Name } }
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - patch
      - update