apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: icea-app
  name: icea-app
  namespace: compass-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icea-app
  template:
    metadata:
      labels:
        app: icea-app
    spec:
      containers:
        - image: dummy-app
          imagePullPolicy: IfNotPresent
          name: icea-app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 100Mi
            requests:
              cpu: 1000m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false