apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucl-tenants-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.minReplicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      hostAliases:
      - ip: {{ .Values.app.gatewayIp | quote }}
        hostnames:
        - {{ .Values.app.gatewayHost | quote }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- with .Values.deployment.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
          {{- end }}
          env:
            - name: LOG_ENABLED
              value: {{ .Values.app.log.enabled | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.app.log.level | quote }}
            - name: RMCONFIG
              value: {{ .Values.app.rmconfig | quote }}
            - name: TENANT_FETCHER_URL
              value: {{ .Values.app.tenantFetcherURL | quote }}
            - name: MAX_CONCURRENT_THREADS_ORGANIZATION_CONTROLLER
              value: {{ .Values.app.max_concurrent_threads.organization_controller | quote }}
            - name: MAX_CONCURRENT_THREADS_FOLDER_CONTROLLER
              value: {{ .Values.app.max_concurrent_threads.folder_controller | quote }}
            - name: MAX_CONCURRENT_THREADS_RESOURCE_GROUP_CONTROLLER
              value: {{ .Values.app.max_concurrent_threads.resource_group_controller | quote }}
            - name: SKIP_SSL_VALIDATION
              value: {{ .Values.app.skipSSLValidation| quote }}
            - name: OAUTH20_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: oauth20-credentials
                  key: client_key
            - name: OAUTH20_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth20-credentials
                  key: client_secret
            - name: OAUTH20_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: oauth20-credentials
                  key: token_url
          volumeMounts:
            - mountPath: /config
              name: resource-manager-config
              readOnly: true
      volumes:
        - name: resource-manager-config
          secret:
            secretName: resource-manager-config
            items:
              - key: rmconfig.yaml
                path: rmconfig.yaml